name: Setup Node.js and Dependencies
description: Sets up Node.js and caches npm dependencies

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '22'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Update npm to latest
      shell: bash
      run: npm install -g npm@latest

    - name: Cache node_modules
      id: cache
      uses: actions/cache@v5
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
